apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llama-32-3b-instruct
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: llama-32-3b-instruct
spec:
  to:
    kind: Service
    name: llama-32-3b-instruct-predictor
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect