FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-21 as build
#WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-21-runtime
WORKDIR /app
COPY --from=build /home/default/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]